# Generated by Django 5.0.6 on 2024-06-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_deliveryoption_name_alter_gender_name_and_more"),
        ("transcripts", "0004_transcriptrequest_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptrequest",
            name="delivery_option",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.deliveryoption",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transcriptrequest",
            name="transcript_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.transcripttype",
            ),
        ),
    ]
