# Generated by Django 5.0.6 on 2024-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_transcriptrequest_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
