# Generated by Django 5.0.6 on 2024-05-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("other_names", models.CharField(blank=True, max_length=30)),
                (
                    "profile_img",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                ("student_id", models.CharField(max_length=20)),
                ("graduation_year", models.DateField(blank=True, null=True)),
                (
                    "verification_documents",
                    models.FileField(blank=True, upload_to="verification_documents/"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.studentprofile",
            ),
        ),
    ]
