# Generated by Django 5.0.6 on 2024-05-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_customuser_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.studentprofile",
            ),
        ),
    ]
