# Generated by Django 5.0.6 on 2024-05-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_studentprofile_step"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="profile_img",
            new_name="profile_image",
        ),
        migrations.RenameField(
            model_name="studentprofile",
            old_name="verification_documents",
            new_name="verification_document",
        ),
    ]
