# Generated by Django 5.0.6 on 2024-05-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_profile_img_studentprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="identification_file",
            field=models.FileField(blank=True, upload_to="identification_documents/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="identification_number",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name="IdentificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short_name", models.CharField(max_length=15)),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="identification_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.identificationtype",
            ),
        ),
    ]
