# Generated by Django 5.0.6 on 2024-05-16 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_studentprofile_identification_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(default="1990-02-22"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(default="email@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_number",
            field=models.CharField(default="541559369", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="postal_address",
            field=models.CharField(default="Jupiter street", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="residential_address",
            field=models.CharField(default="Juputer street", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short_name", models.CharField(max_length=15)),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.gender",
            ),
        ),
    ]
