# Generated by Django 5.0.6 on 2024-05-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_graduatetype_programme_courselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="graduatetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="programme",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
