# Generated by Django 5.0.6 on 2024-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_customuser_profile_studentprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("NOT SUBMITED", "Not Submited"),
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT SUBMITED",
                max_length=20,
            ),
        ),
    ]
