# Generated by Django 5.0.6 on 2024-06-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_studentprofile_verification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="identification_file",
            field=models.FileField(upload_to="identification_documents/"),
        ),
    ]
