# Generated by Django 5.0.6 on 2024-06-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_studentprofile_identification_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="verification_document",
        ),
    ]
