# Generated by Django 5.0.6 on 2024-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_deliveryoption_name_alter_gender_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
